# Generated by Django 3.2.25 on 2025-07-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250725_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='quantity_given',
        ),
        migrations.CreateModel(
            name='AssignedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_given', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.assignment')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phone')),
            ],
        ),
    ]
