# Generated by Django 3.2.25 on 2025-08-13 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250725_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
